export default function handler(req, res) {
  const channels = [
    { id:"hsn1", name:"HSN 1", tag:"Shopping" },
    { id:"qvc1", name:"QVC 1", tag:"Shopping" },
    { id:"gemshopping", name:"Gem Shopping", tag:"Shopping" },
    { id:"tubiaction", name:"Tubi Action", tag:"Movies" },
    { id:"publica", name:"Publica Network", tag:"General" },
    { id:"tubimovies2", name:"Tubi Movies 2", tag:"Movies" },
    { id:"vevopopau", name:"Vevo Pop AU", tag:"Music" },
    { id:"countrytv", name:"Country TV", tag:"Lifestyle" },
    { id:"vevo2au", name:"Vevo 2 AU", tag:"Music" },
    { id:"scheduler145", name:"Scheduler 145", tag:"General" },
    { id:"powernation", name:"PowerNation AU", tag:"Cars" },
    { id:"kartoon", name:"Kartoon Channel", tag:"Kids" },
    { id:"toongoggles", name:"Toon Goggles AU", tag:"Kids" },
    { id:"babyshark", name:"Baby Shark TV", tag:"Kids" },
    { id:"disney", name:"Disney", tag:"Kids" },
    { id:"nickelodeon", name:"Nickelodeon", tag:"Kids" },
    { id:"ryanfriends", name:"Ryan & Friends", tag:"Kids" },
    { id:"supersimple", name:"Super Simple Songs", tag:"Kids" },
    { id:"comet", name:"COMET TV", tag:"Sci-Fi" },
    { id:"tintv", name:"TIN TV", tag:"General" },
    { id:"tubidrama", name:"Tubi Drama", tag:"Movies" },
    { id:"stirr10", name:"Stirr 10", tag:"General" },
    { id:"bloombergeu", name:"Bloomberg EU", tag:"News" },
    { id:"rakutenawesome", name:"Rakuten People Are Awesome", tag:"Lifestyle" },
    { id:"petcollective", name:"Pet Collective", tag:"Animals" },
    { id:"gousa", name:"GoUSA", tag:"Travel" },
    { id:"wpt", name:"World Poker Tour", tag:"Sports" },
    { id:"failarmy", name:"FailArmy", tag:"Comedy" },
    { id:"jflgags", name:"Just For Laughs Gags", tag:"Comedy" },
    { id:"homeshammer", name:"Homes Under The Hammer", tag:"Reality" },
    { id:"baywatch", name:"Baywatch", tag:"Series" },
    { id:"rakutengermany", name:"Rakuten Germany", tag:"General" },
    { id:"yahoofinance", name:"Yahoo Finance", tag:"News" },
    { id:"dealnodeal", name:"Deal or No Deal", tag:"Game Show" },
    { id:"haunttv", name:"Haunt TV", tag:"Horror" },
    { id:"estrellatv", name:"Estrella TV", tag:"General" },
    { id:"yugioh", name:"Yu-Gi-Oh!", tag:"Anime" },
    { id:"midsomer", name:"Midsomer Murders", tag:"Crime" },
    { id:"ntduk", name:"NTD UK", tag:"News" },
    { id:"sportsgrid", name:"SportsGrid", tag:"Sports" },
    { id:"tennisintl", name:"Tennis Channel Intl", tag:"Sports" },
    { id:"dwnews", name:"DW News", tag:"News" },
    { id:"france24", name:"France 24 EN", tag:"News" },
    { id:"redbull", name:"Red Bull TV", tag:"Sports" },
    { id:"nasa", name:"NASA TV Public", tag:"Docs" },
    { id:"pbskids", name:"PBS Kids", tag:"Kids" },
    { id:"clubbingtv", name:"Clubbing TV", tag:"Music" }
  ];

  res.status(200).json(channels);
      }
