export default function handler(req, res) {
  const channels = [
    { id: "hsn1", name: "HSN 1" },
    { id: "qvc1", name: "QVC 1" },
    { id: "gemshopping", name: "Gem Shopping Network" },
    { id: "tubiaction", name: "Tubi Action" },
    { id: "publica", name: "Publica Network 50" },
    { id: "tubimovies2", name: "Tubi Movies 2" },
    { id: "vevopopau", name: "Vevo Pop AU" },
    { id: "countrytv", name: "Country TV" },
    { id: "vevo2au", name: "Vevo 2 AU" },
    { id: "scheduler145", name: "Scheduler 145" },
    { id: "powernation", name: "PowerNation" },
    { id: "kartoon", name: "Kartoon Channel" },
    { id: "toongoggles", name: "Toon Goggles" },
    { id: "babyshark", name: "Baby Shark TV" },
    { id: "disney", name: "Disney" },
    { id: "nickelodeon", name: "Nickelodeon" },
    { id: "ryanfriends", name: "Ryan and Friends" },
    { id: "supersimple", name: "Super Simple Songs" },
    { id: "comet", name: "Comet TV" },
    { id: "tintv", name: "Tin TV" },
    { id: "tubidrama", name: "Tubi Drama" },
    { id: "stirr10", name: "Stirr 10" },
    { id: "bloombergeu", name: "Bloomberg Europe" },
    { id: "rakutenawesome", name: "Rakuten Awesome People" },
    { id: "petcollective", name: "The Pet Collective" },
    { id: "gousa", name: "Go USA" },
    { id: "wpt", name: "World Poker Tour" },
    { id: "failarmy", name: "FailArmy" },
    { id: "jflgags", name: "Just For Laughs Gags" },
    { id: "homeshammer", name: "Homes Under The Hammer" },
    { id: "baywatch", name: "Baywatch" },
    { id: "rakutengermany", name: "Rakuten Germany" },
    { id: "yahoofinance", name: "Yahoo Finance" },
    { id: "dealnodeal", name: "Deal or No Deal" },
    { id: "haunttv", name: "Haunt TV" },
    { id: "estrellatv", name: "Estrella TV" },
    { id: "yugioh", name: "Yu-Gi-Oh!" },
    { id: "midsomer", name: "Midsomer Murders" },
    { id: "ntduk", name: "NTD UK" },
    { id: "sportsgrid", name: "SportsGrid" },
    { id: "tennisintl", name: "Tennis Channel International" },
    { id: "dwnews", name: "DW News" },
    { id: "france24", name: "France 24 English" },
    { id: "redbull", name: "Red Bull TV" },
    { id: "nasa", name: "NASA TV" },
    { id: "pbskids", name: "PBS Kids" },
    { id: "clubbingtv", name: "Clubbing TV" }
  ];

  res.status(200).json(channels);
      }
